sequenceDiagram
    %% Nominal scenario – Uc1 Control Entry
    participant User
    participant UC_Uc1ControlEntry as System
    participant AccessPoint
    participant Camera

    Note over System: Pre-condition: Security System configured

    User        ->> System      : reqReadSecurityCard
    System      ->> Camera      : takeSnapshot
    System      ->> System      : validateSecurityCard
    System      ->> User        : displayCardStatus

    User        ->> System      : reqScanBiometricData
    User        ->> System      : scanBiometricData
    System      ->> System      : authenticateBiometricData
    System      ->> User        : displayAuthenticationStatus

    System      ->> AccessPoint : logEntryData
    System      ->> AccessPoint : unlockAccessPoint
    AccessPoint -->> System      : AP_Unlocked
