flowchart TD
    SS11_1["SS11-1: Two Independent Security Checks (Constraint)"]

    SS11_1 --> SS11_2["SS11-2: Employee ID Card Identification - Entry (Functional Requirement)"]
    SS11_1 --> SS11_3["SS11-3: Employee ID Card Identification - Exit (Functional Requirement)"]
    SS11_1 --> SS11_4["SS11-4: Biometric Scan (Functional Requirement)"]
    SS11_1 --> SS11_5["SS11-5: Time Between Two Independent Checks (Constraint)"]
    SS11_5 --> SS11_6["SS11-6: Configure Time Between Two Independent Checks (Functional Requirement)"]

    SS11_2 --> SS11_7["SS11-7: Three Attempts On Employee ID Entry (Functional Requirement)"]
    SS11_4 --> SS11_8["SS11-8: Three Attempts On Biometric Data Entry (Functional Requirement)"]
    SS11_3 --> SS11_9["SS11-9: Three Attempts On Employee ID Exit (Functional Requirement)"]

    SS11_2 --> SS11_15["SS11-15: Visualization of Security Card Check Status - Entry (Functional Requirement)"]
    SS11_3 --> SS11_16["SS11-16: Visualization of Security Card Check Status - Exit (Functional Requirement)"]
    SS11_4 --> SS11_17["SS11-17: Visualization of Biometric Data Check Status (Functional Requirement)"]

    SS11_7 --> SS11_14["SS11-14: Disabling User Account (Functional Requirement)"]
    SS11_8 --> SS11_14
    SS11_9 --> SS11_14

    SS11_10["SS11-10: Denied Entry Notification (Functional Requirement)"]
    SS11_11["SS11-11: Denied Exit Notification (Functional Requirement)"]
    SS11_12["SS11-12: Alarm - Entry (Functional Requirement)"]
    SS11_13["SS11-13: Alarm - Exit (Functional Requirement)"]

    SS11_7 --> SS11_10
    SS11_8 --> SS11_10
    SS11_9 --> SS11_11
    SS11_10 --> SS11_12
    SS11_11 --> SS11_13
