@startuml
left to right direction

actor User
actor Administrator
actor Camera
actor AccessPoint as "Access Point"

rectangle "Security System" {
    (Uc1: Control Entry) 
    (Uc2: Control Exit) 
    (Uc3: Configure Security System)

    User --> (Uc1: Control Entry)
    User --> (Uc2: Control Exit)

    Administrator --> (Uc1: Control Entry)
    Administrator --> (Uc2: Control Exit)
    Administrator --> (Uc3: Configure Security System)

    Camera --> (Uc1: Control Entry)

    "Access Point" --> (Uc1: Control Entry)
    "Access Point" --> (Uc2: Control Exit)
}
@enduml
